name: paw_watch
description: "A gamified real-life cat rescue community app built with Flutter & Firebase."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2

  # State management
  provider: ^6.1.2

  # Location
  geolocator: ^13.0.1
  geocoding: ^3.0.0

  # Maps
  google_maps_flutter: ^2.9.0

  # Image
  image_picker: ^1.1.2

  # ML Kit
  google_mlkit_image_labeling: ^0.13.0

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  shared_preferences: ^2.5.5
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  url_launcher: ^6.3.1
  video_player: ^2.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/